### ISSUE TITLE
nginx proxy manager configuration

### ISSUE THREAD

**Issue by TWART016** [go-vikunja/frontend#28]
Hi,

I have running a nginx proxy manager instance in docker.
Now I want to configure vikunja with nginx proxy manager.

The vikunja instance in available from the WAN. Just the login failed: `Network Error`
```
// 20211005000721
// http://192.168.178.15:3456/api/v1/login

{
  "message": "missing or malformed jwt"
}
```

In npm I set the domain name with 
Scheme http
Forward Hostname / IP: 192.168.178.15
Forward Port: 10002
SSL Certificate
No Advanced configuration

docker-compose von vikunja:
```
version: '3'

services:
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    image: vikunja/frontend:unstable
    ports:
      - 10002:80
    environment:
      VIKUNJA_API_URL: http://192.168.178.15:3456/api/v1/
    restart: unless-stopped

```

Does anyone have a proxy configuration for npm?

**Comment by kolaente** [comment]
Not sure about nginx proxy manager, but have you seen the nginx reverse proxy example [in the docs](https://vikunja.io/docs/full-docker-example/#example-with-nginx-as-proxy)?

**Comment by TWART016** [comment]
> Not sure about nginx proxy manager, but have you seen the nginx reverse proxy example [in the docs](https://vikunja.io/docs/full-docker-example/#example-with-nginx-as-proxy)?

I know this example. But in nginx proxy manager it looks a bit different.

In this issue there is a similar problem.
https://github.com/go-vikunja/api/issues/2#issuecomment-878383991

This is the config for the host
```
server {
  set $forward_scheme http;
  set $server         "192.168.178.15";
  set $port           10002;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443;

  server_name todo.mydomain;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-10/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-10/privkey.pem;

  access_log /data/logs/proxy_host-5.log proxy;

  location / {
    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}

```

**Comment by kolaente** [comment]
So the file at conf.d/include/proxy.conf contains the proxy config adapted from the docs? Where do you proxy the api requests? If all is set up correctly, you should be able to reach /api/v1/info through the proxy - on the same domain/ip +port as the frontend.

Or you could just continue to expose the api ports and use the api directly, but that kind of defeats the purpose of a proxy.

I'm not sure if I can help you here, while I know my way around nginx I don't know how the nginx proxy manager is different. You might want to ask in the forum, someone else might be able to help you there.

**Comment by TWART016** [comment]
I created a topic in the forum
https://community.vikunja.io/t/nginx-proxy-manager-configuration/385

This is the configuration of npm. It is automatic stored in the volume /data/nginx/proxy_host.

As you can see in the docker-compose https://github.com/go-vikunja/frontend/issues/28#issue-1015683710 the api is available with port 3456.

**Comment by TWART016** [comment]
I removed the line from the docker-compose. Now I can login and there is no error with the public domain.

If I open the interal IP:Port I cannot login because the sign in account is `Sign in to your Vikunja account on 192.168.178.15:10002` and not `Sign in to your Vikunja account on 192.168.178.15:3456`. 

it is not possible to use a local login in parallel?

**Comment by kolaente** [comment]
> it is not possible to use a local login in parallel?

It should be possible but you will probably need to manually change the ip address in Vikunja's frontend.

**Comment by TWART016** [comment]
Ok thanks. For the end user this is not ideal but it works.

**Comment by TheBig-O** [comment]
So, I had the same issue and sorted out a viable solution for using NGINX Proxy Manager with a Docker install of Vikunja. I've tried to detail the method here: https://github.com/TheBig-O/Vikunja-NGINX-Proxy-Manager

**Comment by kolaente** [comment]
@TheBig-O That looks great! Do you want to submit a PR to add this to the docs?

**Comment by TheBig-O** [comment]
@kolaente, I want to try one more thing tonight to see if I can streamline this option a bit. If it works, I'll submit that. If not, I'll go with the posted recommendation. Glad this helped.

**Comment by TheBig-O** [comment]
Submitted a PR. Hopefully, the revised and shortened wording is still clear.

**Comment by DrProphet0** [comment]
Hi,

so I tried following the new guide https://github.com/TheBig-O/Vikunja-NGINX-Proxy-Manager but I kept failing, after much trial and error I figured a way to do it from the UI.

First to get it up and running I used docker compose
I like to put everything in a custom docker network so I don't have ports exposed, if you don't mind you will have to uncomment them
```
version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: vikunja
    volumes:
      - /path/to/vikunja/db:/var/lib/postgresql/data
    restart: unless-stopped
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
    #ports:
    #  - 3456:3456
    volumes: 
      - /path/to/vikunja/files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    image: vikunja/frontend
    #ports:
    #  - 80:80
    restart: unless-stopped
    
    ```
went on to create a docker-compose.yml file and running `docker-compose up -d`

After it has spun up the containers it assigns them automatically a network  in my case vikunja_default
For this setup to work you must assign the containers on the same network your NPM is
If you have ports exposed in the yaml you don't have to.

For example I have my npm running on npm_default
To assign my containers I execute 

`docker network connect vikunja_api_1 npm_default `
`docker network connect vikunja_frontend_1 npm_default `

You don't have to assign the DB container

Running a command to check that everything is on the same network 

`docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }} {{range .NetworkSettings.Networks}} {{.IPAddress}}{{end}}' | sed 's#^/##';`

![2](https://user-images.githubusercontent.com/76781738/147372128-7706e87d-a516-4d77-967c-9d77380edfb7.png)

So in this case 
vikunja_api_1 has 192.168.0.23
vikunja_frontend_1 has 192.168.0.22
nginx proxy manager  192.168.0.2

Just make sure to note that these IP addresses will be different on your system just try to find them following the above command 

Now for the fun part 
Let's go to npm

Click to Add a Proxy Host

![1](https://user-images.githubusercontent.com/76781738/147372191-c4929564-7d68-4445-b267-e32cadb6aa8b.png)

Then fill in the form 

- Your domain name or subdomain of choice
- The vikunja frontend IP address as found before
- At port 80

![3](https://user-images.githubusercontent.com/76781738/147372236-e13bf3eb-14c8-4616-ac0a-bfe72a7cd160.png)

Then we move to the next tab Custom Locations and we will add a new location

![4](https://user-images.githubusercontent.com/76781738/147372259-eee1392a-bd18-4a0b-8ff9-be6ca8feef84.png)

We will fill the form

- The same location as in the nginx configuration
- The vikunja api address in the Forward IP 
- At port 3456

![5](https://user-images.githubusercontent.com/76781738/147372484-1fc740ac-756a-4748-90a6-d5314d2d6325.png)


We will click the cog

![6](https://user-images.githubusercontent.com/76781738/147372297-cfde6ffd-c81e-487a-99f2-7a539a9b486a.png)

and add last line
`client_max_body_size 20M;`
exactly as in the original nginx setup

We can finally request a new SSL Certificate and Save our configuration!

![7](https://user-images.githubusercontent.com/76781738/147372490-2411a3d8-73b2-40ce-8c15-5f66adc66257.png)


That's it we did it! 
Time to have fun!

Hope this helps someone <3
